services:
  db:
    image: mysql:8.4.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sushidb
    ports:
      - 3307:3306
    volumes:
      - ./my.conf:/etc/mysql/my.cnf
      - ./initial_data:/docker-entrypoint-initdb.d