CREATE TABLE users (
  id INT AUTO_INCREMENT,
  user_name VARCHAR(50) NOT NULL,
  mail_address VARCHAR(254) NOT NULL UNIQUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME DEFAULT '9999-12-31 23:59:59',
  PRIMARY KEY (id)
);

CREATE TABLE workspaces (
  id INT AUTO_INCREMENT,
  workspace_name VARCHAR(50) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE workspace_members (
  id INT AUTO_INCREMENT,
  workspace_id INT NOT NULL,
  user_id INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (workspace_id) REFERENCES workspaces (id),
  FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE channels (
  id INT AUTO_INCREMENT,
  workspace_id INT NOT NULL,
  channel_name VARCHAR(50) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (workspace_id) REFERENCES workspaces (id)
);

CREATE TABLE channel_members (
  id INT AUTO_INCREMENT,
  channel_id INT NOT NULL,
  user_id INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (channel_id) REFERENCES channels (id),
  FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE messages (
  id INT AUTO_INCREMENT,
  user_id INT NOT NULL,
  channel_id INT NOT NULL,
  parent_id INT DEFAULT NULL,
  content TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME DEFAULT '9999-12-31 23:59:59',
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users (id),
  FOREIGN KEY (channel_id) REFERENCES channels (id),
  FOREIGN KEY (parent_id) REFERENCES messages (id),
  INDEX idx_channel_id_created_at (channel_id, created_at DESC),
  FULLTEXT (content) WITH PARSER mecab
);
