services:
  db:
    image: neo4j:5.26
    environment:
      - NEO4J_AUTH=none # 検証用のため認証無効
      - NEO4J_PLUGINS=["apoc"]
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
      - ./init_query.cypher:/init_query.cypher
volumes:
  neo4j-data: